### ISSUE TITLE
Infografia Edwin Ortiz Cruz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-1-infografia-EdwinOrtiz1412#2]
[Infografia _Edwin Ortiz Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-EdwinOrtiz1412/files/9420079/Infografia._Edwin.Ortiz.Cruz.pdf)

**Comment by NoeliaGlez** [comment]
17.5% contiene faltas de ortografía

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
